apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: drone-cleanup
  namespace: drone
spec:
  schedule: "0 19 * * 1"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: drone-cleanup
            image: lachlanevenson/k8s-kubectl
            command: ["sh", "-c", 
            "for job in $(kubectl get jobs -n drone | awk '$4 ~ /^[2-9][0-9]d/' | awk '{print $1}'); do kubectl delete job $job -n drone; done"]
          serviceAccountName: drone-deploy
          restartPolicy: Never
  successfulJobsHistoryLimit: 3