apiVersion: v1
kind: ServiceAccount
metadata:
  name: drone-deploy
  namespace: drone

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: drone-deploy
  namespace: drone
rules:
  - apiGroups: ["extensions", "batch"]
    resources: ["deployments", "jobs"]
    verbs: ["get","list","patch","update","delete"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: drone-deploy
  namespace: drone
subjects:
  - kind: ServiceAccount
    name: drone-deploy
    namespace: drone
roleRef:
  kind: ClusterRole
  name: drone-deploy
  apiGroup: rbac.authorization.k8s.io
