---
- hosts: loadbalancer
  become: true

  tasks:
    - name: Copy the nginx config file
      template:
        src: nginx.conf.j2
        dest: /etc/nginx.conf

    - name: Run nginx in a container in node 1
      docker_container:
        name: nginx
        image: nginx:1.14
        volumes:
          - /etc/nginx.conf:/etc/nginx/nginx.conf
        detach: yes
        restart_policy: unless-stopped
        ports: 
          - "80:80"
          - "443:443"